Criação do algoritmo de Machine Learning com Regressão Linear. <br>
As etapas serão:
* Separação dos dados em: Treinamento, Teste e Validação.
* Tratamento dos dados.
* Treinamento do modelo.
* Avaliação de métricas.

# <font color='yellow'> Obtendo os Dados

In [16]:
# Bibliotecas
import pandas as pd

In [29]:
df = pd.read_csv("../dataset/df_clean.csv")
df.head()

   tamanho_m2  idade_imovel  num_banheiros  proximidade_metro  preco_aluguel
0  146.480693            39              4           0.400952   15216.435887
1  117.486173            20              3           1.508170   10888.829048
2  113.577868            37              4           0.543368   13961.798360
3  113.578527            19              3           0.510779   14082.040617
4  209.539682            28              3           0.539166   22377.220420

<font color='lightgreen'>

# <font color='yellow'> Separação dos Dados

A separação dos dados ocorre na primeira etapa. Isso evita Data Leakage e overfitting dos modelos. <br>
*obs:* isso impede de dados 'futuros' vazarem para o 'passado'.

In [1]:
# Bibliotecas
from sklearn.model_selection import train_test_split

In [11]:
X = df_raw.drop(columns=["preco_aluguel"])
y = df_raw["preco_aluguel"]

In [12]:
# Visualizando
X.head()

   Unnamed: 0  tamanho_m2  idade_imovel  num_banheiros  proximidade_metro
0           0  146.480693            39              4           0.400952
1           1  117.486173            20              3           1.508170
2           2  113.577868            37              4           0.543368
3           3  113.578527            19              3           0.510779
4           4  209.539682            28              3           0.539166

In [13]:
y.head()

0    15216.435887
1    10888.829048
2    13961.798360
3    14082.040617
4    22377.220420
Name: preco_aluguel, dtype: float64